# Deploy with:
# gcloud app deploy .\target\randomquotes.0.1.9.jar --appyaml .\app.yaml

runtime: java
env: flex
service: randomquotes

handlers:
  - url: /.*
    script: this field is required, but ignored